name: HotsPractice
main: net.hotsmc.practice.HotsPractice
version: 1.0
softdepend: [HotsCore]
commands:
  practice:
  duel:
  party:
    aliases: [p]
  inv:
  event:
  spectate:
    aliases: [spec]
  gf: